version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: energy-backend
    container_name: backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    image: energy-frontend
    container_name: frontend
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
